### ISSUE TITLE
No mention of LBRule as prereq for deploying to Azure SF

### ISSUE THREAD

**Issue by snobu** [Azure-Samples/service-fabric-dotnet-getting-started#14]
In https://github.com/Azure-Samples/service-fabric-dotnet-getting-started#voicemailbox
>The application includes a web UI accessible at http://<clusteraddress>:8081/voicemailbox/ and a set of web APIs that can be used to interact with the actor methods.

It isn't immediately obvious that i have to go and manually create a load balancing rule first (for port 8081/TCP) if i want this deployed in Azure Service Fabric - see this other related Issue here https://github.com/Azure/azure-content/issues/5763

Please add a paragraph stating this is a prerequisite for all sample applications that require a LBRule.

**Comment by vturecek** [comment]
Will do, we have a lot more documentation on the way around this that we'll link to from here.
