### ISSUE TITLE
Chatter is missing prebuild.ps1 file

### ISSUE THREAD

**Issue by TheBeardedLlama** [Azure-Samples/service-fabric-dotnet-getting-started#25]
related to issue #24 

this file is required for VSTS to successfully build the project based on the suggested build agent setup (using the NetworkService account) from [your own docs](https://azure.microsoft.com/en-us/documentation/articles/service-fabric-set-up-continuous-integration/)

[the asp.net docs](https://msdn.microsoft.com/en-us/Library/vs/alm/Build/azure/deploy-aspnet5) for reference

**Comment by vturecek** [comment]
Were you able to get VSTS to build the project by following the steps here? https://msdn.microsoft.com/en-us/Library/vs/alm/Build/azure/deploy-aspnet5

**Comment by TheBeardedLlama** [comment]
That is what I was referring to, yes. But I had to spend some time trying to figure out what's missing and why the project would not build in VSTS.
I've raised a separate issue for the global.json as that was required as well.
