### ISSUE TITLE
sfproj issue

### ISSUE THREAD

**Issue by bklooste** [Azure-Samples/service-fabric-dotnet-getting-started#27]
If i move any of the sfproj projects to a subdirectory it creates an Output path error this makes it hard transitioning the samples ( eg remove the sfproj , create a sub dir , move it in and re add to solution ) .,

**Comment by 24X7** [comment]
Yep, seeing the exact same issue, same scenario.

**Comment by mthalman-msft** [comment]
That's probably because you didn't update the relative paths for the <Import> elements in the .sfproj file.  Be sure to update both the Project and Condition attributes of those elements.  And, of course, you'd also need to update the relative paths of the references to your service projects.

**Comment by mthalman-msft** [comment]
That's probably because you didn't update the relative paths for the &ltImport&gt; elements in the .sfproj file. Be sure to update both the Project and Condition attributes of those elements. And, of course, you'd also need to update the relative paths of the references to your service projects.
