### ISSUE TITLE
Project references in Chatter service

### ISSUE THREAD

**Issue by MuffinMan10110** [Azure-Samples/service-fabric-dotnet-getting-started#30]
@seanmck I notice that the `Chat.Domain` is a class library for the purpose of sharing the service interfaces between each of the services and the web api. However, I'm wondering why those interfaces/models were defined in the web api project and then linked into the `Chat.Domain` project?

Why not just reference the class library in the web api in the same way that the `Chat.Service` references it?

As an aside, this workflow actually fixes an issue that I'm running into. By referencing the class library from all projects the solution builds, but when publishing to the SF cluster I get a build error because the asp.net core web api isn't building the dependent class library. It just seems dirty to have to define the service definitions in the web api and link the code files to the class library. Thoughts?

**Comment by vturecek** [comment]
Chatter was based on asp.net 5 (pre-release). At that time, we couldn't link to Class Library projects, so we did this as a work-around. Even today, there are some problems with build configurations in Visual Studio when trying to reference an x64 .csproj from an .xproj.
