### ISSUE TITLE
The project does not have a package action set

### ISSUE THREAD

**Issue by s-leonard** [Azure-Samples/service-fabric-dotnet-getting-started#32]
I've down loaded and successfully built the VisualObject sample solutions and I have a local cluster setup and running. However running or publishing the application outputs the following deployment error 

> The project does not have a package action set

`1>------ Build started: Project: VisualObjects.ActorService, Configuration: Debug x64 ------
2>------ Build started: Project: VisualObjects.WebService, Configuration: Debug x64 ------
2>  VisualObjects.WebService -> C:\@projects\Research\service-fabric-dotnet-getting-started-master\Actors\VisualObjects\VisualObjects.WebService\bin\x64\Debug\VisualObjects.WebService.exe
1>  VisualObjects.ActorService -> C:\@projects\Research\service-fabric-dotnet-getting-started-master\Actors\VisualObjects\VisualObjects.ActorService\bin\x64\Debug\VisualObjects.ActorService.exe
3>------ Build started: Project: VisualObjects, Configuration: Debug x64 ------
4>------ Publish started: Project: VisualObjects, Configuration: Debug x64 ------
-------- Package started: Project: VisualObjects, Configuration: Debug x64 ------
4>The project does not have a package action set.
========== Build: 3 succeeded, 0 failed, 1 up-to-date, 0 skipped ==========
========== Publish: 0 succeeded, 1 failed, 0 skipped ==========`

I cant find anything online to suggest what this might be?

**Comment by karolz-ms** [comment]
This is unfortunately a known bug that will be fixed in the next Fabric tooling release.

For now the workaround is to unload the Fabric project, then reload. That should allow building the project successfully.

**Comment by s-leonard** [comment]
That worked thanks

**Comment by boarmanc** [comment]
Worked for me! I also had to launch VS as administrator for the SF local cluster to start up.

**Comment by byronbayer** [comment]
Publishing from Visual Studio to Service Fabric gave me this issue as well. 
Your suggestion fixed the issue.
Thanks

**Comment by juanluelguerre** [comment]
Worked for me too! 
Thansks

**Comment by andrewkrgeo** [comment]
Unload/Reload project Worked for me on SDK 6.1.480
