### ISSUE TITLE
Black page with a green border

### ISSUE THREAD

**Issue by lmachetti** [Azure-Samples/service-fabric-dotnet-getting-started#36]
I'm able to build, deploy, debug and start the project (just downloaded).
But unfortunately, I only see a black page with a green border.
No triangle at all.

![image](https://cloud.githubusercontent.com/assets/20458398/17810706/0200e03c-661f-11e6-8670-f7ebf1fe12ce.png)

**Comment by masnider** [comment]
If you look in the browser console are there any javascript errors? looks like either the backend service is not running or there is some connection issue.

**Comment by lmachetti** [comment]
Thank you for a prompt response.
On Chrome I get:
         GET http://localhost:8081/favicon.ico 503 (Service Unavailable)
On Internet Explorer:
        HTML1527: Expected DOCTYPE. It's better to add a valid HTML5 doctype "<!DOCTYPE html>".
File: visualobjects, line: 1, column: 1

I don't think that these are causing the issue, do you?
Thanks

**Comment by msfussell** [comment]
when you connect to the cluster with Service Fabric explorer, so you see the service running like in the attached screen shot?
![image](https://cloud.githubusercontent.com/assets/11199644/17845199/0596575e-67f5-11e6-9c4e-ad56a6b9d060.png)

**Comment by lmachetti** [comment]
Yes.. see below (and I'm also able to see it running on Visual Studio)

![image](https://cloud.githubusercontent.com/assets/20458398/17897566/e7168cc0-6954-11e6-84a0-d18cb5be4483.png)

**Comment by mvanhelmont** [comment]
You are running Windows 7? I have the same problem on my Windows 7 machine. Windows 7 does not support server WebSockets.

**Comment by lmachetti** [comment]
Exactly I'm running Windows 7. If so, is there any workaround? Thank you very much

**Comment by mvanhelmont** [comment]
You need to use a library that support websockets on Windows 7 see topic here
http://stackoverflow.com/questions/11039438/using-websocket-on-windows7

**Comment by masnider** [comment]
Hi @lmachetti were you able to get this working?

**Comment by lmachetti** [comment]
Unfortunately not. It's too time consuming to write the code to use a different library.
I think this example should run on Windows 7 out of the box, because It's one of the most used Operating System.
Anyway, thank you all for your support.
