### ISSUE TITLE
System.Net.HttpListenerException - AlphabetPartitions --> Alphabet.Web HttpCommunicationListener.cs

### ISSUE THREAD

**Issue by iamjz** [Azure-Samples/service-fabric-dotnet-getting-started#44]
I'm running the solution by hitting F5 on your AlphabetPartitions solution. But I'm getting an error on HttpCommunicationListener.cs under Alphabet.Web on the follow method:  OpenAsync(CancellationToken cancellationToken).

It is complaining:  System.Net.HttpListenerException - {"The process cannot access the file because it is being used by another process"}.

**Comment by iamjz** [comment]
any ideas on this one?

**Comment by grahamehorner** [comment]
I believe HttpListener is complaining about the http port, it may be in use by iis or other, also make sure your only running a single instance of the service on the port

**Comment by vturecek** [comment]
Yup this just means the port is already taken.

**Comment by iamjz** [comment]
thanks!
