### ISSUE TITLE
I'm sure i'm doing this wrong but could you have a look?

### ISSUE THREAD

**Issue by snobu** [Azure-Samples/service-fabric-dotnet-getting-started#50]
Just deployed **VisualObjects** to Service Fabric on Azure, opened 8081/TCP in the Load Balancer and i'm getting **503 Service Unavailable** when i hit the URL with a browser:

```
http://servicefabricname.region.cloudapp.azure.com:8081/
```

The ServiceManifest does say 8081/TCP for the Web listener.
What am i doing wrong? Works just fine in the local emulator.

**Comment by masnider** [comment]
Is the load balancer configured to forward 8081 to 8081 on the particular node type that VO is running on? Can you confirm the listening address that VO reports that it is listening on via SFX?

**Comment by snobu** [comment]
@masnider My bad.

It's actually `/visualobjects`, like this:<br>http://servicefabricname.region.cloudapp.azure.com:8081/visualobjects

But why is the HTTP endpoint returning a 503 instead of something more appropriate like a 404? Was very misleading.

**Comment by masnider** [comment]
Just to confirm - it's working now? Re: 503 vs. 404 - That's just the behavior of the http server/endpoint. I'm sure you could customize/modify it if you wished.

**Comment by snobu** [comment]
Yes, it's working fine, it was just a matter of wrong URL. Thanks.
