### ISSUE TITLE
The example throw System.TypeInitializationException after a successful build with a clean downloaded code

### ISSUE THREAD

**Issue by tecsined** [Azure-Samples/service-fabric-dotnet-getting-started#65]
I download the code and with updated nugget package and not updated package the code is throwing this exception:

I have installed SF version: 5.7.198.9494

System.TypeInitializationException occurred
  HResult=0x80131534
  Message=The type initializer for 'Microsoft.ServiceFabric.Actors.Runtime.ActorRuntime' threw an exception.
  Source=Microsoft.ServiceFabric.Actors
  StackTrace:
   at Microsoft.ServiceFabric.Actors.Runtime.ActorRuntime.RegisterActorAsync[TActor](Func`3 actorServiceFactory, TimeSpan timeout, CancellationToken cancellationToken)
   at ActorBackendService.Program.Main() in C:\service-fabric-demo\src\GettingStartedApplication\ActorBackendService\Program.cs:line 34

Inner Exception 1:
InvalidCastException: Unable to cast COM object of type 'System.__ComObject' to interface type 'IFabricNodeContextResult2'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{472BF2E1-D617-4B5C-A91D-FABED9FF3550}' failed due to the following error: No such interface supported (Exception from HRESULT: 0x80004002 (E_NOINTERFACE)).

**Comment by ctapang** [comment]
I fixed this by updating VS 2017 Community to 15.3.5, all Nuget modules to their latest versions, and also the .Net Core SDK to version 2.0.

Now, I'm having a different problem: the override method CreateServiceInstanceListeners in WebService.cs is not being called. This must be a config issue, but being a service fabric newbie, I have no idea where to look.

**Comment by ctapang** [comment]
I take that back: the method CreateServiceInstanceListeners in WebService.cs is being called. This method defines nested anonymous methods in two levels, and the second level is not being called.

**Comment by tecsined** [comment]
I try updating my VS (Enterprise) but still I get the error

**Comment by ctapang** [comment]
How about the .Net Core SDK and Nuget modules? Did you try updating those too? I updated SF also, it turns out, to v6.

**Comment by ctapang** [comment]
However, I still couldn't get it to work, even if this problem you described is fixed. Microsoft should work to get these samples to work. Even the samples in the VS 2017 add-on don't work. At this point I have given up on SF, and am using good old App Services instead.

**Comment by VipulM-MSFT** [comment]
Please ensure that Visual Studio 2017 is updated. Then uninstall all Service Fabric SDK and runtimes and then reinstall the 2.8 SDK. This will install the 6.0 runtime on the machine. The 2.8 SDK packages required 6.0 and higher runtime. 

We did have a period of few weeks couple of months back where the samples were updated but the new SDK and runtime were not published as well as the Azure clusters were not upgraded. This should not be an issue now.
